apiVersion: apps/v1
kind: Deployment
metadata:
  name: arithmetic-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arithmetic-service
  template:
    metadata:
      labels:
        app: arithmetic-service
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
        - name: arithmetic-service
          image: tarashregistry.azurecr.io/arithmetic-service:v1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: arithmetic-service
spec:
  type: LoadBalancer
  selector:
    app: arithmetic-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
